-- Create the businesses table
create table businesses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  business_name text not null,
  google_place_id text,
  raw_data jsonb,
  status text default 'new'
);

-- Enable Row Level Security (RLS)
alter table businesses enable row level security;

-- Create a policy that allows anyone to insert (since this is a public onboarding form)
-- In a real app, you might want to restrict this or use a service role key server-side.
create policy "Enable insert for all users" on businesses for insert with check (true);

-- Create a policy that allows reading only your own data (if we had auth)
-- For now, we might just allow public read if needed, or keep it private.
-- create policy "Enable read access for all users" on businesses for select using (true);
