-- Create the businesses table
create table if not exists businesses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  business_name text not null,
  google_place_id text,
  raw_data jsonb,
  status text default 'new'
);

-- Enable Row Level Security (RLS)
alter table businesses enable row level security;

-- Create a policy that allows anyone to insert
do $$ 
begin
  if not exists (
    select 1 from pg_policies 
    where tablename = 'businesses' and policyname = 'Enable insert for all users'
  ) then
    create policy "Enable insert for all users" on businesses for insert with check (true);
  end if;
end $$;
